### ISSUE TITLE
Proxy property is not working on iOS devices

### ISSUE THREAD

**Issue by zevsst** [FubarDevelopment/restsharp.portable#57]
Hello.

Please have a look at the bug description and one of the possible solutions in the comment section.
http://stackoverflow.com/questions/24340570/restsharp-portable-restclient-proxy-property-is-not-working/36165221#36165221

Thanks.

**Comment by fubar-coder** [comment]
Thank you, I'll take a look at this problem. Sadly, the main reason why I added the Proxy property access using reflection, was, that the property should be available according to the PCL contract, but it was missing when used on a Xamarin supported platform. I'll take a look if this workaround can be removed now.

**Comment by zevsst** [comment]
Not at all, man.

I could not set Proxy property of HttpClientHandler in my implementation directly. Only the solution contains reflection works good for me. While I was trying to set Proxy directly I caught an exception which said that there was no setter for property Proxy. I guess it might be happened only for iOS platform. 
Maybe this help you.

`public virtual async Task PreAuthenticate(IHttpClient client, IHttpRequestMessage request, ICredentials credentials)
        {
            await Task.Yield();

            // Below is a fix with proxy for iOS devices
            var defaultHttpClient = client as DefaultHttpClient;

            var httpClient = defaultHttpClient?.Client;
            if (httpClient != null)
            {
                var httpClientType = httpClient.GetType();
                var handlerFieldInfo = httpClientType.GetField("handler", BindingFlags.NonPublic | BindingFlags.FlattenHierarchy);

                var handler = handlerFieldInfo?.GetValue(httpClient) as HttpClientHandler;
                if (handler != null && handler.SupportsProxy)
                {
                    var handlerType = handler.GetType();

                    var proxyFieldInfo = handlerType.GetField("proxy", BindingFlags.NonPublic);
                    if (proxyFieldInfo != null)
                    {
                        if (proxyFieldInfo.FieldType == typeof(IWebProxy))
                        {
                            var proxy = proxyFieldInfo.GetValue(handler);
                            if (proxy == null && webProxy != null && !proxyFieldInfo.IsInitOnly)
                            {
                                proxyFieldInfo.SetValue(handler, webProxy);
                            }
                        }
                    }
                }
            }
        }`

**Comment by fubar-coder** [comment]
Fixed in 3.1.1

**Comment by zevsst** [comment]
The problem still exists.

**Comment by fubar-coder** [comment]
Please try 3.1.2. It's difficult for me to test, because I don't have an iOS device/emulator ATM

**Comment by zevsst** [comment]
I have tested 3.1.2 and the problem still exists. Please see my thoughts [here](https://github.com/FubarDevelopment/restsharp.portable/commit/4d57ab3721ea7238d12470e792c434b4209cc60e)

**Comment by adamfisher** [comment]
I am still seeing this in 3.3.0 using the latest version of Xamarin at the time of writing.

`Method 'HttpClientHandler.set_Proxy' not found.`

Using:
**Xamarin.iOS**
Version: 9.6.2.4
Build date: 2016-05-05 17:43:01-0400

**Xamarin.Android**
Version: 6.0.4.0
